CREATE TABLE portfolio
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(128)                            NOT NULL,
    link            VARCHAR(255)                            NOT NULL,
    additional_info TEXT,
    is_active       BOOLEAN DEFAULT TRUE                    NOT NULL,
    student_id      UUID,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_portfolio PRIMARY KEY (id)
);

ALTER TABLE portfolio
    ADD CONSTRAINT uc_portfolio_name UNIQUE (name);

ALTER TABLE portfolio
    ADD CONSTRAINT FK_PORTFOLIO_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);
