CREATE TABLE skills
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(128),
    is_active     BOOLEAN DEFAULT TRUE                    NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    category_id   BIGINT,
    education_id  BIGINT,
    speciality_id BIGINT,
    CONSTRAINT pk_skills PRIMARY KEY (id)
);


