CREATE TABLE applications
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id        VARCHAR(32),
    history_path   VARCHAR(255),
    result         VARCHAR(32),
    result_message VARCHAR(255),
    is_active      BOOLEAN DEFAULT TRUE                    NOT NULL,
    recruiter_id   UUID,
    student_id     UUID,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_applications PRIMARY KEY (id)
);

ALTER TABLE applications
    ADD CONSTRAINT uc_applications_chat UNIQUE (chat_id);

ALTER TABLE applications
    ADD CONSTRAINT uc_applications_history_path UNIQUE (history_path);

ALTER TABLE applications
    ADD CONSTRAINT FK_APPLICATIONS_ON_RECRUITER FOREIGN KEY (recruiter_id) REFERENCES recruiters (id);

ALTER TABLE applications
    ADD CONSTRAINT FK_APPLICATIONS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);