CREATE TABLE experiences
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_id      BIGINT,
    student_id      UUID,
    position        VARCHAR(255)                            NOT NULL,
    additional_info TEXT,
    start_date      date                                    NOT NULL,
    end_date        date                                    NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_companies_students PRIMARY KEY (id)
);

ALTER TABLE companies_students
    ADD CONSTRAINT FK_COMPANIES_STUDENTS_ON_EDUCATION FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE companies_students
    ADD CONSTRAINT FK_COMPANIES_STUDENTS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);