CREATE TABLE institution
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    education_id BIGINT,
    student_id   UUID,
    start_year   INTEGER                                 NOT NULL,
    end_year     INTEGER                                 NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_educations_students PRIMARY KEY (id)
);

ALTER TABLE educations_students
    ADD CONSTRAINT FK_EDUCATIONS_STUDENTS_ON_EDUCATION FOREIGN KEY (education_id) REFERENCES education (id);

ALTER TABLE educations_students
    ADD CONSTRAINT FK_EDUCATIONS_STUDENTS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);