CREATE TABLE skills
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(128),
    is_active     BOOLEAN DEFAULT TRUE                    NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    category_id   BIGINT,
    education_id  BIGINT,
    speciality_id BIGINT,
    CONSTRAINT pk_skills PRIMARY KEY (id)
);

ALTER TABLE skills
    ADD CONSTRAINT uc_skills_name UNIQUE (name);

ALTER TABLE skills
    ADD CONSTRAINT FK_SKILLS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE skills
    ADD CONSTRAINT FK_SKILLS_ON_EDUCATION FOREIGN KEY (education_id) REFERENCES education (id);

ALTER TABLE skills
    ADD CONSTRAINT FK_SKILLS_ON_SPECIALITY FOREIGN KEY (speciality_id) REFERENCES specialities (id);