CREATE TABLE experiences
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    position        VARCHAR(255)                            NOT NULL,
    additional_info TEXT,
    start_date      date                                    NOT NULL,
    end_date        date                                    NOT NULL,
    company_id      BIGINT,
    student_id      UUID,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_experiences PRIMARY KEY (id)
);

ALTER TABLE experiences
    ADD CONSTRAINT FK_EXPERIENCES_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE experiences
    ADD CONSTRAINT FK_EXPERIENCES_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);