ALTER TABLE skills
    ADD CONSTRAINT UC_SKILLS_NAME UNIQUE (name);

ALTER TABLE skills
    ADD CONSTRAINT FK_SKILLS_ON_SPECIALITY FOREIGN KEY (speciality_id) REFERENCES specialities (id);

ALTER TABLE skills
    ADD CONSTRAINT FK_SKILLS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);
