CREATE TABLE institution
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_year   INTEGER                                 NOT NULL,
    end_year     INTEGER                                 NOT NULL,
    education_id BIGINT,
    student_id   UUID,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_institution PRIMARY KEY (id)
);

ALTER TABLE institution
    ADD CONSTRAINT FK_INSTITUTION_ON_EDUCATION FOREIGN KEY (education_id) REFERENCES education (id);

ALTER TABLE institution
    ADD CONSTRAINT FK_INSTITUTION_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);